"""
iOS Shortcuts 快捷指令对接 API

提供简化的 REST 端点，可被 iOS Shortcuts 直接调用:
1. 快速获取今日摘要
2. 快速获取待办列表
3. 快速获取周报
4. 快速创建提醒

用法示例（Shortcuts → Get Contents of URL）:
- GET http://server/api/shortcuts/today → 获取今日录音摘要
- GET http://server/api/shortcuts/todos → 获取待办清单（纯文本）
- GET http://server/api/shortcuts/weekly → 获取周报（纯文本）
"""
import json
import logging
from datetime import datetime, timezone, timedelta

from fastapi import APIRouter
from fastapi.responses import PlainTextResponse

from app.database.connection import get_db

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/shortcuts", tags=["shortcuts"])


@router.get("/today")
async def shortcut_today_summary():
    """
    今日摘要 — iOS Shortcuts 友好格式（纯文本）

    返回今天所有录音的标题 + AI 摘要
    """
    db = await get_db()
    try:
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        cursor = await db.execute(
            "SELECT title, analysis, duration, scene_type FROM recordings WHERE DATE(created_at) = ? ORDER BY created_at DESC",
            (today,),
        )
        rows = [dict(r) for r in await cursor.fetchall()]

        if not rows:
            return PlainTextResponse("📭 今天还没有录音记录")

        lines = [f"📅 {datetime.now().strftime('%Y年%m月%d日')} 录音摘要", f"共 {len(rows)} 条录音", ""]

        for i, rec in enumerate(rows, 1):
            lines.append(f"📌 {i}. {rec['title']}")
            if rec.get("analysis"):
                try:
                    analysis = json.loads(rec["analysis"])
                    summary = analysis.get("summary", "")
                    if summary:
                        lines.append(f"   {summary}")
                except (json.JSONDecodeError, TypeError):
                    pass
            lines.append("")

        return PlainTextResponse("\n".join(lines))
    finally:
        await db.close()


@router.get("/todos")
async def shortcut_todos():
    """
    待办清单 — iOS Shortcuts 友好格式（纯文本）

    可以直接添加到 iOS 提醒事项 / 日历
    """
    db = await get_db()
    try:
        cursor = await db.execute(
            "SELECT task, assignee, deadline, recording_id FROM todos WHERE status = 'pending' ORDER BY created_at DESC"
        )
        todos = [dict(r) for r in await cursor.fetchall()]

        if not todos:
            return PlainTextResponse("✅ 没有待处理的待办事项")

        lines = [f"📋 待办清单 ({len(todos)} 项)", ""]
        for i, todo in enumerate(todos, 1):
            task = todo["task"]
            deadline = f" ⏰{todo['deadline'][:10]}" if todo.get("deadline") else ""
            assignee = f" 👤{todo['assignee']}" if todo.get("assignee") else ""
            lines.append(f"☐ {i}. {task}{assignee}{deadline}")

        return PlainTextResponse("\n".join(lines))
    finally:
        await db.close()


@router.get("/weekly")
async def shortcut_weekly():
    """
    周报摘要 — iOS Shortcuts 友好格式

    可以直接发送到备忘录 / 邮件
    """
    db = await get_db()
    try:
        week_ago = (datetime.now(timezone.utc) - timedelta(days=7)).isoformat()

        cursor = await db.execute(
            "SELECT COUNT(*) FROM recordings WHERE created_at >= ?", (week_ago,)
        )
        rec_count = (await cursor.fetchone())[0]

        cursor = await db.execute(
            "SELECT COUNT(*) FROM todos WHERE created_at >= ?", (week_ago,)
        )
        new_todos = (await cursor.fetchone())[0]

        cursor = await db.execute(
            "SELECT COUNT(*) FROM todos WHERE status = 'done' AND updated_at >= ?",
            (week_ago,),
        )
        done_todos = (await cursor.fetchone())[0]

        cursor = await db.execute(
            "SELECT COALESCE(SUM(duration), 0) FROM recordings WHERE created_at >= ?",
            (week_ago,),
        )
        total_duration = (await cursor.fetchone())[0]
        duration_min = int(total_duration / 60)

        period = f"{(datetime.now() - timedelta(days=7)).strftime('%m/%d')} - {datetime.now().strftime('%m/%d')}"

        lines = [
            f"📊 AiRecord 周报 ({period})",
            "",
            f"🎙️ 录音: {rec_count} 条",
            f"⏱️ 总时长: {duration_min} 分钟",
            f"📝 新待办: {new_todos} 项",
            f"✅ 已完成: {done_todos} 项",
            "",
            "— Generated by AiRecord AI —",
        ]

        return PlainTextResponse("\n".join(lines))
    finally:
        await db.close()
